### ISSUE TITLE
Drag-and-drop of a scene file from Chrome's download bar fails silently on Mac

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#228] opened 2015-11-12 16:50 UTC

**Comment by louh** [comment] 2016-02-03 17:13
Can you tell me more what this is about?

**Comment by patriciogonzalezvivo** [comment] 2016-02-03 17:33
If you download a scene.yaml, will apear down in the browser screen as an icon... right?
That icon can be dragged. If you try to drag&drop it back into tangramPlay it will not work. I saw Brett trying to do couple of times in the past before we were saving into memory (remembering the last scene).

**Comment by louh** [comment] 2016-02-03 18:23
In Chrome, right?
I just tried it and it's working for me. Not sure if something else has changed between then and now. But can you give it another try?

**Comment by patriciogonzalezvivo** [comment] 2016-02-03 21:32
Still not working on chrome

**Comment by louh** [comment] 2016-02-03 22:34
Oh, interesting -- when I tried it earlier, I was on my Windows machine at home, where it worked fine. But on my Macbook, it does not. Just so I can confirm that you are seeing the same thing: does it show the drag & drop overlay, but nothing happens if you drop?

**Comment by patriciogonzalezvivo** [comment] 2016-02-04 13:41
exactly!

**Comment by louh** [comment] 2016-02-04 15:37
On investigation, the `drop` event (which receives the file) is never fired when dragging a file from the Chrome download bar on Mac. I can't seem to find any other information about this. I'm considering the possibility this is a browser bug.

**Comment by louh** [comment] 2016-02-04 15:41
I've just tried this here: https://css-tricks.com/examples/DragAndDropFileUploading/

Same deal, it will accept a file when dropped from file system, but there is no response to a drop from the download bar.

**Comment by louh** [comment] 2016-02-04 15:52
I am logging this bug here: https://code.google.com/p/chromium/issues/detail?id=584311

**Comment by louh** [comment] 2016-02-11 20:53
The bug I filed is a duplicate of: https://code.google.com/p/chromium/issues/detail?id=234931

There's a comment there that is extremely useful:

> For what it's worth, we found that dropEffect was set to 'none', and setting dropEffect manually on dragover fixes the problem.

```
var _handleDragOver = function (e) {
   var effect = e.dataTransfer && e.dataTransfer.dropEffect
   var effectAllowed = e.dataTransfer && e.dataTransfer.effectAllowed
   if (effect != 'none' || effectAllowed == 'none') return

   e.dataTransfer.dropEffect = effectAllowed == 'move' ? 'move' : 'copy'
 }
```

**Closed** 2016-02-12 13:45 UTC
Labels: bug
