### ISSUE TITLE
try http prefix with Opening from URL

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-play#315] opened 2016-04-19 19:32 UTC
in the Open Scene File from URL flow, if you copy a URL from a browser window it may be copied without the 'http://' or 'https://' – if you try to open this URL, Play will fail with a "Failed to Fetch" error – in this case maybe the 'http://' prefix could be added to the URL if it's missing.

**Comment by louh** [comment] 2016-04-19 21:13
Yup - I had disabled the input's built-in url validation in order to allow more potential kinds of inputs, but this has not been implemented yet. Dupe of #301, but I am closing that one in favor of this one since I did not leave a description in it

**Closed** 2016-04-22 15:54 UTC
Labels: enhancement, in progress
